# A generic, single database configuration for Alembic.

[alembic]
# Path to migration scripts
script_location = alembic

# Template used to generate migration file names
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file as well as the filename.
# string value, e.g. UTC, GMT0, EST, US/Eastern, etc.
timezone = UTC

# max length of characters in --autogenerate title
# max_length_provided_by_script = 40

# database URL
sqlalchemy.url = postgresql+asyncpg://postgres:postgres@localhost:5432/hcl_db

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.

[logging]
default_level = INFO
